backend:
  name: git-gateway
  branch: trunk

media_folder: "src/images"
public_folder: "/images"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        delete: false
        file: "src/index.md"
        slug: "{{slug}}"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/home.html"}
          - {label: "Tab Title", name: "title", widget: "string"}
          - {label: "SEO Meta Title", name: "metaTitle", widget: "string", required: false}
          - {label: "SEO Meta Description", name: "metaDesc", widget: "string", required: false}
          - {label: "Social Image", name: "socialImage", widget: "image", required: false}
          - {label: "Social Image Fallback", name: "socialImageFallback", widget: "image", required: false}
          - label: "Intro"
            name: "intro"
            widget: "object"
            fields:
              - {label: "Section Title", name: "title", widget: "string", default: "Intro", required: false}
              - {label: "Heading", name: "heading", widget: "string", default: "Hi, I'm Ben Hamilton"}
              - {label: "Copy", name: "copy", widget: "markdown", minimal: true, required: false}
          - label: "Work"
            name: "work"
            widget: "object"
            fields:
              - {label: "Section Title", name: "title", widget: "string", default: "Work", required: false}
              - {label: "Heading", name: "heading", widget: "string", default: "Work"}
              - {label: "Item Link Text", name: "itemLinkText", widget: "string", default: "View case study"}
          - label: "Writing"
            name: "writing"
            widget: "object"
            fields:
              - {label: "Section Title", name: "title", widget: "string", default: "Thoughts", required: false}
              - {label: "Heading", name: "heading", widget: "string", default: "Thoughts"}
              - {label: "Copy", name: "copy", widget: "markdown", minimal: true, required: false}
              - label: "Articles"
                name: "articles"
                collapsed: false
                add_to_top: true
                label_singular: "article"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Date", name: "date", widget: "date", default: "", format: "DD.MM.YY"}
                  - {label: "URL", name: "url", widget: "string"}
  - label: "Work"
    name: "work"
    folder: "src/work"
    slug: "{{slug}}"
    preview_path: "work/{{slug}}"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/work-item.html"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "SEO Meta Title", name: "metaTitle", widget: "string", required: false}
      - {label: "SEO Meta Description", name: "metaDesc", widget: "string", required: false}
      - {label: "Social Image", name: "socialImage", widget: "image", required: false}
      - {label: "Social Image Fallback", name: "socialImageFallback", widget: "image", required: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: true}
      - {label: "Display Order", name: "displayOrder", widget: "number", value_type: "int", default: "0"}
      - {label: "Excerpt", name: "excerpt", widget: "markdown", minimal: true}
      - {label: "Summary", name: "summary", widget: "markdown", minimal: true, required: false}
      - label: "Components"
        name: "components"
        label_singular: "component"
        widget: "list"
        types:
          - label: "Info"
            name: "info"
            widget: "object"
            fields:
              - {label: "Client", name: "client", widget: "string", required: false}
              - {label: "Agency", name: "agency", widget: "string", required: false}
              - {label: "Expertise", name: "expertise", widget: "string", required: false}
              - {label: "Project Outcomes", name: "outcomes", widget: "markdown", minimal: true, required: false}
              - {label: "URL", name: "url", widget: "string", required: false}
              - {label: "Link Text", name: "linkText", widget: "string", required: false}
          - label: "Single Image"
            name: "singleImage"
            widget: "object"
            fields:
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Image Fallback", name: "imageFallback", widget: "image"}
              - {label: "Alt Text", name: "imageAlt", widget: "string"}
              - {label: "Caption", name: "caption", widget: "string", required: false}
              - {label: "Full-height", name: "fullheight", widget: "boolean", default: false}
          - label: "Double Image"
            name: "doubleImage"
            widget: "object"
            fields:
              - {label: "First Image", name: "image1", widget: "image"}
              - {label: "First Image Fallback", name: "image1Fallback", widget: "image"}
              - {label: "First Image Alt Text", name: "image1Alt", widget: "string"}
              - {label: "First Image Caption", name: "image1Caption", widget: "string", required: false}
              - {label: "Second Image", name: "image2", widget: "image"}
              - {label: "Second Image Fallback", name: "image2Fallback", widget: "image"}
              - {label: "Second Image Alt Text", name: "image2Alt", widget: "string"}
              - {label: "Second Image Caption", name: "image2Caption", widget: "string", required: false}
          - label: "Testimonial"
            name: "testimonial"
            widget: "object"
            fields:
              - {label: "Quote", name: "quote", widget: "markdown", minimal: true}
              - {label: "Author", name: "author", widget: "string", required: false}
              - {label: "Author's Company", name: "authorCo", widget: "string", required: false}
          - label: "Video"
            name: "video"
            widget: "object"
            fields:
              - {label: "Video", name: "video", widget: "file"}
              - {label: "Embed video (get iframe code direct from source)", name: "videoEmbed", widget: "string"}
              - {label: "Full-height", name: "fullheight", widget: "boolean", default: false}
  - label: "Globals"
    name: "globals"
    files:
      - label: "Site Data"
        name: "site_data"
        delete: false
        file: "src/_data/site.json"
        fields:
          - {label: "Site Name", name: "name", widget: "string"}
          - {label: "Site URL", name: "url", widget: "string"}
          - {label: "Author Name", name: "authorName", widget: "string"}
          - {label: "Favicon path (e.g: /images/favicon.png)", name: "faviconPath", widget: "string", default: "/images/meta/bh-hanger.svg"}
      - label: "Sidebar"
        name: "sidebar"
        delete: false
        file: "src/_data/sidebar.json"
        fields:
          - label: "Images"
            name: "images"
            widget: "object"
            fields:
              - {label: "Primary Theme Image", name: "theme1Image", widget: "image"}
              - {label: "Primary Theme Image Fallback", name: "theme1ImageFallback", widget: "image"}
              - {label: "Primary Image Alt Text", name: "theme1ImageAlt", widget: "string"}
              - {label: "Seconary Theme Image", name: "theme2Image", widget: "image"}
              - {label: "Seconary Theme Image Fallback", name: "theme2ImageFallback", widget: "image"}
              - {label: "Secondary Image Alt Text", name: "theme2ImageAlt", widget: "string"}
              - {label: "High-Contrast Theme Image", name: "themeHCImage", widget: "image"}
              - {label: "High-Contrast Theme Image Fallback", name: "themeHCImageFallback", widget: "image"}
              - {label: "High-Contrast Image Alt Text", name: "themeHCImageAlt", widget: "string"}
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Copy", name: "copy", widget: "markdown", minimal: true, required: false}
          - {label: "Email Address", name: "email", widget: "string", required: false}
          - {label: "Email Text", name: "emailText", widget: "string", required: false}
          - {label: "Social URL", name: "socialUrl1", widget: "string", required: false}
          - {label: "Social Text", name: "socialText1", widget: "string", required: false}
      - label: "Footer"
        name: "footer"
        delete: false
        file: "src/_data/footer.json"
        fields:
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Copy", name: "copy", widget: "markdown", minimal: true, required: false}
          - {label: "Button URL", name: "buttonUrl", widget: "string", required: false}
          - {label: "Button Text", name: "buttonText", widget: "string", required: false}
          - {label: "Design Credit", name: "designCredit", widget: "string"}