backend:
  name: git-gateway
  branch: trunk

media_folder: "src/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home"
        delete: false
        file: "src/index.md"
        slug: "{{slug}}"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/home.html"}
          - {label: "Tab Title", name: "title", widget: "string"}
          - {label: "SEO Meta Title", name: "metaTitle", widget: "string", required: false}
          - {label: "SEO Meta Description", name: "metaDesc", widget: "string", required: false}
          - {label: "Social Image", name: "socialImage", widget: "image", required: false}
          - label: "Intro"
            name: "intro"
            widget: "object"
            fields:
              - {label: "Section Title", name: "title", widget: "string", default: "Intro", required: false}
              - {label: "Heading", name: "heading", widget: "string", default: "Hi, I'm Ben Hamilton"}
              - {label: "Copy", name: "copy", widget: "markdown", minimal: true, required: false}
          - label: "Work"
            name: "work"
            widget: "object"
            fields:
              - {label: "Section Title", name: "title", widget: "string", default: "Work", required: false}
              - {label: "Heading", name: "heading", widget: "string", default: "Workies!"}
              - {label: "Item Link Text", name: "itemLinkText", widget: "string", default: "View case study"}
          - label: "Writing"
            name: "writing"
            widget: "object"
            fields:
              - {label: "Section Title", name: "title", widget: "string", default: "Work", required: false}
              - {label: "Heading", name: "heading", widget: "string", default: "Thinkings"}
              - {label: "Copy", name: "copy", widget: "markdown", minimal: true, required: false}