backend:
  name: git-gateway
  branch: trunk
  name: github
  repo: georgehieron/ben-hamilton
publish_mode: editorial_workflow
media_folder: "src/images"
public_folder: "/images"
# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home"
        delete: false
        file: "src/index.md"
        slug: "{{slug}}"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/njk.njk"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "SEO Meta Title", name: "metaTitle", widget: "string", required: false}
          - {label: "SEO Meta Description", name: "metaDesc", widget: "string", required: false}
          - {label: "Social Image", name: "socialImage", widget: "image", required: false}