backend:
  name: git-gateway
  branch: trunk
publish_mode: editorial_workflow
media_folder: "src/images"
public_folder: "/images"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home"
        delete: false
        file: "src/index.md"
        slug: "{{slug}}"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/home.html"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "SEO Meta Title", name: "metaTitle", widget: "string", required: false}
          - {label: "SEO Meta Description", name: "metaDesc", widget: "string", required: false}
          - {label: "Social Image", name: "socialImage", widget: "image", required: false}
          - label: Intro
            name: intro
            widget: object
            fields:
              - {label: Title, name: title, widget: string, default: "Intro"}
              - {label: Main, name: main, widget: string, default: "Hi, I'm Ben Hamilton"}